In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [5]:
data = pd.read_csv("E:/kc_house_data.csv")
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [7]:
data1 = data.drop(columns=['id','date'])
data1

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,662500.0,3,2.50,3560,9796,1.0,0,0,3,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,468000.0,2,1.00,1160,6000,1.0,0,0,4,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,310000.0,3,1.00,1430,19901,1.5,0,0,4,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,400000.0,3,1.75,1370,9680,1.0,0,0,4,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,530000.0,5,2.00,1810,4850,1.5,0,0,3,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,650000.0,4,3.00,2950,5000,2.0,0,3,3,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,395000.0,3,2.00,1890,14040,2.0,0,0,3,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,485000.0,4,1.00,1600,4300,1.5,0,0,4,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,189000.0,2,1.00,1200,9850,1.0,0,0,4,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,230000.0,3,1.00,1250,9774,1.0,0,0,4,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
20,385000.0,4,1.75,1620,4980,1.0,0,0,4,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2000000.0,3,2.75,3050,44867,1.0,0,4,3,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,285000.0,5,2.50,2270,6300,2.0,0,0,3,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,252700.0,2,1.50,1070,9643,1.0,0,0,3,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,329000.0,3,2.25,2450,6500,2.0,0,0,4,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,233000.0,3,2.00,1710,4697,1.5,0,0,5,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,937000.0,3,1.75,2450,2691,2.0,0,0,3,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
27,667000.0,3,1.00,1400,1581,1.5,0,0,5,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
28,438000.0,3,1.75,1520,6380,1.0,0,0,3,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,719000.0,4,2.50,2570,7173,2.0,0,0,3,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,399950.0,2,1.00,710,1157,2.0,0,0,4,7,710,0,1943,0,98102,47.6413,-122.329,1370,1173
21584,380000.0,3,2.50,1260,900,2.0,0,0,3,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,270000.0,3,2.50,1870,5000,2.0,0,0,3,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,505000.0,2,2.50,1430,1201,3.0,0,0,3,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,385000.0,3,2.50,1520,1488,3.0,0,0,3,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,414500.0,2,1.50,1210,1278,2.0,0,0,3,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,347500.0,3,2.50,2540,4760,2.0,0,0,3,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,1222500.0,4,3.50,4910,9444,1.5,0,0,3,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,572000.0,4,2.75,2770,3852,2.0,0,0,3,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,475000.0,3,2.25,1190,1200,3.0,0,0,3,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,1088000.0,5,3.75,4170,8142,2.0,0,2,3,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,350000.0,4,2.75,2500,5995,2.0,0,0,3,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,520000.0,2,2.25,1530,981,3.0,0,0,3,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,679950.0,5,2.75,3600,9437,2.0,0,0,3,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,1575000.0,4,3.25,3410,10125,2.0,0,0,3,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,541800.0,4,2.50,3118,7866,2.0,0,2,3,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,810000.0,4,3.00,3990,7838,2.0,0,0,3,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,1537000.0,5,3.75,4470,8088,2.0,0,0,3,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,467000.0,3,2.50,1425,1179,3.0,0,0,3,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,224000.0,3,1.75,1500,11968,1.0,0,0,3,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,507250.0,3,2.50,2270,5536,2.0,0,0,3,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,610685.0,4,2.50,2520,6023,2.0,0,0,3,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,1007500.0,4,3.50,3510,7200,2.0,0,0,3,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,475000.0,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [8]:
x = data1.drop(columns=['price'])

In [9]:
type(x)

pandas.core.frame.DataFrame

In [10]:
x.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [11]:
y= data1['price']

In [13]:
y= pd.DataFrame({'price':y})

In [15]:
y.head()

      price
0  221900.0
1  538000.0
2  180000.0
3  604000.0
4  510000.0

In [20]:
x.shape

(21613, 18)

In [21]:
y.shape

(21613, 1)

In [22]:
data1.shape

(21613, 19)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [25]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(17290, 18)
(17290, 1)
(4323, 18)
(4323, 1)

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
regress = LinearRegression()

In [29]:
regress.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
print(regress.coef_)

[[-3.20279315e+04  3.60409149e+04  1.06391432e+02  1.32288285e-01
   1.01348768e+04  5.38860457e+05  5.19958026e+04  2.76632242e+04
   9.55651532e+04  6.86621575e+01  3.77292746e+01 -2.51780015e+03
   2.10768444e+01 -5.49685041e+02  6.10241682e+05 -2.06289119e+05
   2.11939640e+01 -3.47658777e-01]]

In [31]:
print(regress.intercept_)

[3956635.4751063]

In [33]:
y_pred = regress.predict(x_test)

In [35]:
y_pred.shape

(4323, 1)

In [37]:
y_pred = pd.DataFrame(y_pred , columns = ['y_pred'])

In [38]:
y_pred

            y_pred
0     6.400582e+05
1     4.766775e+05
2     7.076587e+05
3     7.138413e+05
4     2.322725e+05
5     6.595712e+05
6     5.369024e+05
7     7.780838e+05
8     5.553637e+05
9     5.299509e+05
10    2.699644e+05
11    4.399385e+05
12    5.830452e+05
13    3.628213e+05
14    5.198668e+05
15    9.253439e+05
16    3.242659e+05
17    8.004299e+05
18    4.865485e+05
19    4.576604e+05
20    2.621972e+05
21    5.666724e+05
22    1.337982e+06
23    8.490888e+05
24    5.013034e+05
25    6.963390e+05
26    3.732448e+05
27    2.029447e+05
28    4.421556e+05
29    6.360622e+05
...            ...
4293  2.488652e+05
4294  9.842897e+05
4295  5.471433e+05
4296  5.179816e+05
4297  4.243014e+05
4298  2.829274e+05
4299  3.939892e+05
4300  5.799319e+05
4301  2.875557e+05
4302  8.980153e+05
4303  4.351541e+05
4304  1.294778e+06
4305  3.503865e+05
4306  2.499828e+05
4307  2.645541e+05
4308  4.108232e+05
4309  5.752678e+05
4310  6.679113e+05
4311  3.452927e+05
4312  1.821104e+05
4313  4.009036e+05
4314  4.634480e+05
4315  7.950049e+05
4316  7.831697e+05
4317  2.309148e+05
4318  1.041397e+06
4319  3.896548e+05
4320  3.605216e+05
4321  1.387672e+06
4322  3.679381e+05

[4323 rows x 1 columns]

In [39]:
y_test

           price
15544   459000.0
17454   445000.0
21548  1057000.0
3427    732350.0
8809    235000.0
3294    555000.0
275     365000.0
8736    685000.0
6161    525000.0
19832   449950.0
17232   280000.0
1305    428000.0
12702   575000.0
12717   313100.0
17327   637500.0
8196    732000.0
13      400000.0
13412   829000.0
16484   469500.0
14761   537000.0
1675    224000.0
17478   597500.0
19226  1059000.0
8083    720000.0
17237   569950.0
18122   576925.0
19836   285000.0
10046   235000.0
13341   280000.0
8040    440000.0
...          ...
5395    299800.0
9742    999950.0
19355   370000.0
12011   395000.0
3922    431500.0
7958    203000.0
10903   331500.0
15521   727160.0
14366   165000.0
8962    750000.0
2122    405000.0
8829    603500.0
628     543500.0
8881    269000.0
7504    397000.0
15936   345000.0
16635   705000.0
1610    667500.0
17333   430000.0
1291    170000.0
6127    309950.0
4691    423000.0
10757   850000.0
4235    700000.0
1381    234000.0
13597   965000.0
9648    359950.0
18627   260000.0
9553   1795000.0
14200   418000.0

[4323 rows x 1 columns]

In [40]:
y_pred.index = y_test.index

In [41]:
y_pred

             y_pred
15544  6.400582e+05
17454  4.766775e+05
21548  7.076587e+05
3427   7.138413e+05
8809   2.322725e+05
3294   6.595712e+05
275    5.369024e+05
8736   7.780838e+05
6161   5.553637e+05
19832  5.299509e+05
17232  2.699644e+05
1305   4.399385e+05
12702  5.830452e+05
12717  3.628213e+05
17327  5.198668e+05
8196   9.253439e+05
13     3.242659e+05
13412  8.004299e+05
16484  4.865485e+05
14761  4.576604e+05
1675   2.621972e+05
17478  5.666724e+05
19226  1.337982e+06
8083   8.490888e+05
17237  5.013034e+05
18122  6.963390e+05
19836  3.732448e+05
10046  2.029447e+05
13341  4.421556e+05
8040   6.360622e+05
...             ...
5395   2.488652e+05
9742   9.842897e+05
19355  5.471433e+05
12011  5.179816e+05
3922   4.243014e+05
7958   2.829274e+05
10903  3.939892e+05
15521  5.799319e+05
14366  2.875557e+05
8962   8.980153e+05
2122   4.351541e+05
8829   1.294778e+06
628    3.503865e+05
8881   2.499828e+05
7504   2.645541e+05
15936  4.108232e+05
16635  5.752678e+05
1610   6.679113e+05
17333  3.452927e+05
1291   1.821104e+05
6127   4.009036e+05
4691   4.634480e+05
10757  7.950049e+05
4235   7.831697e+05
1381   2.309148e+05
13597  1.041397e+06
9648   3.896548e+05
18627  3.605216e+05
9553   1.387672e+06
14200  3.679381e+05

[4323 rows x 1 columns]

In [42]:
y_test.join(y_pred)

           price        y_pred
15544   459000.0  6.400582e+05
17454   445000.0  4.766775e+05
21548  1057000.0  7.076587e+05
3427    732350.0  7.138413e+05
8809    235000.0  2.322725e+05
3294    555000.0  6.595712e+05
275     365000.0  5.369024e+05
8736    685000.0  7.780838e+05
6161    525000.0  5.553637e+05
19832   449950.0  5.299509e+05
17232   280000.0  2.699644e+05
1305    428000.0  4.399385e+05
12702   575000.0  5.830452e+05
12717   313100.0  3.628213e+05
17327   637500.0  5.198668e+05
8196    732000.0  9.253439e+05
13      400000.0  3.242659e+05
13412   829000.0  8.004299e+05
16484   469500.0  4.865485e+05
14761   537000.0  4.576604e+05
1675    224000.0  2.621972e+05
17478   597500.0  5.666724e+05
19226  1059000.0  1.337982e+06
8083    720000.0  8.490888e+05
17237   569950.0  5.013034e+05
18122   576925.0  6.963390e+05
19836   285000.0  3.732448e+05
10046   235000.0  2.029447e+05
13341   280000.0  4.421556e+05
8040    440000.0  6.360622e+05
...          ...           ...
5395    299800.0  2.488652e+05
9742    999950.0  9.842897e+05
19355   370000.0  5.471433e+05
12011   395000.0  5.179816e+05
3922    431500.0  4.243014e+05
7958    203000.0  2.829274e+05
10903   331500.0  3.939892e+05
15521   727160.0  5.799319e+05
14366   165000.0  2.875557e+05
8962    750000.0  8.980153e+05
2122    405000.0  4.351541e+05
8829    603500.0  1.294778e+06
628     543500.0  3.503865e+05
8881    269000.0  2.499828e+05
7504    397000.0  2.645541e+05
15936   345000.0  4.108232e+05
16635   705000.0  5.752678e+05
1610    667500.0  6.679113e+05
17333   430000.0  3.452927e+05
1291    170000.0  1.821104e+05
6127    309950.0  4.009036e+05
4691    423000.0  4.634480e+05
10757   850000.0  7.950049e+05
4235    700000.0  7.831697e+05
1381    234000.0  2.309148e+05
13597   965000.0  1.041397e+06
9648    359950.0  3.896548e+05
18627   260000.0  3.605216e+05
9553   1795000.0  1.387672e+06
14200   418000.0  3.679381e+05

[4323 rows x 2 columns]